# You should create a common.yaml and overwrite this with something more
# secure
maestro::params::agent_user_password: 'maestro'

maestro::params::repo:
  url: 'https://repo.maestrodev.com/archiva/repository/all'
  username: 'demo'
  password: '...'

# Must specify, otherwise it'll be RPM's 'present', which isn't valid
maestro::agent::agent_version: '2.7.0'


